### ISSUE TITLE
lowpower.h

### ISSUE THREAD

**Issue by sunnyday333** [InScene/lora_weather_station#1]
Hello,

thank you for releasing your code. It is inspiration for me.. But I have a problem with lowpower library, can you add it to your code?  I cannot find this library with LowPower.isWdtTriggered and LowPower.returnToSleep methods included.

Thank you

**Comment by sunnyday333** [comment]
Hello,

can you add lowpower library which you used in your project, please?

**Comment by InScene** [comment]
Hello Sunnyday,

sorry for the late reply, but I was on vacation.
You can find the source of the lowpower library here:
[https://github.com/rocketscream/Low-Power](url)
I hope this will solve your problem.

Regards
Christian

**Comment by sunnyday333** [comment]
Hello InScene,

Thanks for submitting your reference to the Low-Power Library, but this library does not include the ```returnToSleep()``` and ```isWdtTriggered()``` methods that you use in your main weatherstation.ino file on lines 257 and 260 as you can see below:
```c
  for (int i=0; i<sleepcycles; i++) {
    g_wdtFailSafe.resetCnt();
    // Enter power down state for 8 s with ADC and BOD module disabled
    LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);
    // If watchdog not triggered, go back to sleep. End sleep by other interrupt 
     while(!LowPower.isWdtTriggered())
    {
      g_wdtFailSafe.increaseCnt();
      LowPower.returnToSleep();
    }
  }
```
Thank you

**Comment by InScene** [comment]
Hello sunnyday,

I have added the low-power library as a zip file. I hope I got the right one.

A quick note. 
I will be updating this project soon as the TTN V2 I am using is outdated and I need to use TTN V3.
Also, I have switched to Visual Studio Code as Ide, which will make it easier to version the entire project, even with all the libraries included.

Many greetings

**Comment by sunnyday333** [comment]
Hello InScene,

The library you added allows me to compile source codes. I also use VSCode with the platformIO plugin. I'm looking forward to the upgraded version to TTN v3.

Thank you.
